# Generated by Django 3.1.5 on 2021-01-27 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Valve',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=20, unique=True)),
                ('dn', models.IntegerField()),
                ('kvs', models.FloatField()),
                ('price', models.FloatField()),
                ('type_title', models.CharField(max_length=30)),
                ('z', models.FloatField()),
            ],
        ),
    ]
