# Generated by Django 3.1.5 on 2021-01-29 18:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=100, unique=True)),
                ('control_signal', models.CharField(max_length=100, null=True)),
                ('dn', models.IntegerField(null=True)),
                ('equip_type', models.CharField(max_length=100, null=True)),
                ('full_title', models.CharField(max_length=100, null=True)),
                ('kvs', models.FloatField(null=True)),
                ('price', models.FloatField(null=True)),
                ('setting_range', models.CharField(max_length=100, null=True)),
                ('type_title', models.CharField(max_length=100, null=True)),
                ('voltage', models.CharField(max_length=100, null=True)),
                ('z', models.FloatField()),
            ],
        ),
    ]
