# Generated by Django 3.1.5 on 2021-01-29 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0002_equipment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='equipment',
            name='z',
            field=models.FloatField(null=True),
        ),
    ]
