# Generated by Django 3.1.5 on 2021-01-30 10:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0003_auto_20210129_2304'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Valve',
        ),
    ]
