# Generated by Django 3.1.5 on 2021-01-31 19:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('valves', '0004_delete_valve'),
    ]

    operations = [
        migrations.AddField(
            model_name='equipment',
            name='discount_group',
            field=models.CharField(default='temporary_discount_group', max_length=100),
            preserve_default=False,
        ),
    ]
